rl_setting:
  alg: PPO
  algo_hyperparameters:
    batch_size: 128
    learning_rate: !!float 3e-5
    n_epochs: 10
    n_steps: 2048
    seed: 0
    verbose: 1
  policy:
    kwargs:
      activation_fn: ReLU
      net_arch:
      - 64
      - 64
    type: MlpPolicy
  total_timesteps: 5000

env_kwargs:
  observations:
    current_model_state: null
  
  actions:
    joint_torques:
      dim: 15
      torque_max: 5

  initalisation: random_on_mocap_trajectory
    
  rewards:
    motion_imitation:
      exp_const_list: [ 
                        -1,-1,-1,

                      ]
      weight_list: [ 
                        0.3,0.3,0.3,

                      ]
      kernel: 'norm_l2'

  terminations:
    mocap_epi_len: null
    min_base_height:
      threshold: 0.45 
    
  set_on_rack: False
  render: True
  model_name: 'AB3_Session1_humanoid' #'default_humanoid_mocap'
  mocap_data:
    processed_data_path: './data/our_data/marker_data/processed_data/AB3_Session1_Right10_Left10_from_2000_to_2500.npz'
    ik_solns_path: './data/our_data/ik_solns/AB3_Session1_Right10_Left10_from_2000_to_2500.npz'


